### ISSUE TITLE
WIndows server crash when players hit trigger_start 

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#10]
error application: cs2.exe
error module : server.dll
error code: 0xc0000005
error offset: 0x0000000000953011

What it is in crash dialog

**Comment by DEAFPS** [comment]
I believe this is a CSS issue rather than SharpTimer

**Comment by DEAFPS** [comment]
Windows Support for SharpTimer will be added with v0.1.0
