### ISSUE TITLE
Server safety help

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#12]
Someone fuck the top list with something special i think..... Should I worry about the safety ?
![屏幕截图 2023-12-16 005156](https://github.com/DEAFPS/SharpTimer/assets/28674126/c79769a2-3b47-4a13-812b-da39b8849b86)

**Comment by DEAFPS** [comment]
seems like the map you play on uses "fake triggers", make sure the start and end coordinates dont intersect otherwise people will be able to end their run while standing inside the start
