### ISSUE TITLE
custom_exec.cfg should load after map load fully

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#16]
Some maps have build-in convar but not the same as what i set

**Comment by LaplaceTor** [comment]
> thx for the suggestion! alternatively for now you can put your settings into the SharpTimer/config.cfg that one will exec on each round start

I try it but some convars such as roundtime /timelimit should use mp_restartgame later to change it and then it get into a dead loop..... And some maps have their own  cfg applying before game start 
Probably I should ask mapper for removing their cfg?

**Comment by DEAFPS** [comment]
> I found that you hook the players' connect event, try the " host activate: changelevel " event instead?

in 0.1.4 i hook the roundstart event for loading mapdata like respawnpos etc so they can be easily reloaded by calling mp_restartgame 1.

config.cfg and custom_exec.cfg is being loaded OnMapStart. i will try to see if i can delay that so it execs a little after the map has loaded their exec :)
