### ISSUE TITLE
[Bug] ? Team is full

### ISSUE THREAD

**Issue by freakexeuLow** [DEAFPS/SharpTimer#17]
Hey, it looks like something went wrong with the last update because only one person per side is allowed to play. with the previous version (v0.1.1) it works without problems...

Metamod Version: 1275
Cssharp Version: 126v
Sharptimer Version: v0.1.2

![3facda31cdba78baf0533fc45d83a8c0](https://github.com/DEAFPS/SharpTimer/assets/32603929/88a90146-c6f0-4580-8351-06f36250fd85)

and a huge respect for this project, thanks 👍🏼

**Comment by DEAFPS** [comment]
i didnt change anything in these matters, check your config for teamlimits etc

some maps might also enforce their own cfgs

**Comment by freakexeuLow** [comment]
> i didnt change anything in these matters, check your config for teamlimits etc
> 
> some maps might also enforce their own cfgs

I already use your custom_exec cfg with this one https://github.com/DEAFPS/cs-cfg/blob/main/surf.cfg so I don't know what's wrong on my side...I will try again with v0.1.3, but thanks for your answer 👍🏼

**Comment by DEAFPS** [comment]
let me know if you have resolved your issue

**Comment by freakexeuLow** [comment]
> let me know if you have resolved your issue

had to wait a little longer but everything works, thank you ✌🏼
