### ISSUE TITLE
[REQ]: Add checkpoint system

### ISSUE THREAD

**Issue by kus** [DEAFPS/SharpTimer#2]
This is a fantastic plugin.

Do you have any plans to add a checkpoint system?

You can have it so you can enable/disable via server convar.

It can be basic to start:

!checkpoint - sets your checkpoint
!gocheckpoint - goes too your set checkpoint
!prev - goes to your previous checkpoint (nice to have)
!next - goes to your next checkpoint (nice to have)

**Comment by DEAFPS** [comment]
thx for the suggestion, a checkpoint system is on my todo list. ill try to push it out in the next update!
