### ISSUE TITLE
Bug : When timer go up to 1 hour above, the record would not show fully

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#20]
![屏幕截图 2023-12-18 000029](https://github.com/DEAFPS/SharpTimer/assets/28674126/31eb578e-d0cb-4dea-bab1-f786b149bc82)
He fininsh a run in 1:09:02.656 1 hour , 9min , 2 sec

**Comment by DEAFPS** [comment]
i really didnt think that anyone would need longer than AN HOUR TO FINISH A MAP...
good find tho, ill fix it in the next release

**Comment by LaplaceTor** [comment]
> i really didnt think that anyone would need longer than AN HOUR TO FINISH A MAP... good find tho, ill fix it in the next release

A bhop map that hardcore lol...
Probably more record over hours in the future

**Comment by DEAFPS** [comment]
ive updated the 0.1.3 release with the formatting fix
