### ISSUE TITLE
Feature Request : Remove debris collision and damage taken on every player , not using mp_humanteam and mp_solid_teammates instead

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#21]
Unfortunately, mp_autoteambalance 0 is not working now
When set mp_humanteam oneside , only half of the maxplayers can join the game and others can only be spec

**Comment by DEAFPS** [comment]
I had this ready for the 0.1.2 release but unfortunately it caused crashes on windows so ive delayed that feature for a later update. 

for now as a workaround you can use cs2fixes and enable `cs2f_noblock_enable` & `cs2f_block_all_dmg`

unfortunately cs2fixes will break checkpoints for kz tho
