### ISSUE TITLE
Some features wanted 

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#22]
1.!noclip
2.!goto goto someone else
3.!stop stop timer 

Should stop timer when noclip or goto

**Comment by DEAFPS** [comment]
thx gonna be added in 0.1.4

**Comment by LaplaceTor** [comment]
> thx gonna be added in 0.1.4

New wanted: use !spec to save players timer and pos (show onground) and when join team again teleport him to the location

**Comment by LaplaceTor** [comment]
NEW:
Multi zone for bonus
Such as 
!bonus 1 to bonus 1
!addstartzone bonus 1 for bonus 1
!respawnpos bonus 1
!r b1

**Comment by DEAFPS** [comment]
> NEW: Multi zone for bonus Such as !bonus 1 to bonus 1 !addstartzone bonus 1 for bonus 1 !respawnpos bonus 1 !r b1

will be added in next release!

**Comment by LaplaceTor** [comment]
> > NEW: Multi zone for bonus Such as !bonus 1 to bonus 1 !addstartzone bonus 1 for bonus 1 !respawnpos bonus 1 !r b1
> 
> will be added in next release!
> https://github.com/DEAFPS/SharpTimer/commit/78553a60f64b92aa6f5460b99407da9d7395c075
> 
> just in case these are all the changes coming to 0.1.4


About noclip, i mean, everyone can use !noclip but when noclip, stop the time. for bhop and surf it's useful to looking for the right way

**Comment by DEAFPS** [comment]
> About noclip, i mean, everyone can use !noclip but when noclip, stop the time. for bhop and surf it's useful to looking for the right way

thats the difference between going into spectator freecam and actual noclip? i added noclip only for the reason so admins can add fake triggers easily for maps that dont have real ones set up yet

**Comment by LaplaceTor** [comment]
> > About noclip, i mean, everyone can use !noclip but when noclip, stop the time. for bhop and surf it's useful to looking for the right way
> 
> whats the difference between going into spectator freecam and actual noclip? i added noclip only for the reason so admins can add fake triggers easily for maps that dont have real ones set up yet
> 

Alright 👍 you're right

**Comment by DEAFPS** [comment]
i might add that other suggestion youve made about !spec, that sounds like something worth adding

**Comment by LaplaceTor** [comment]
> > About noclip, i mean, everyone can use !noclip but when noclip, stop the time. for bhop and surf it's useful to looking for the right way
> 
> whats the difference between going into spectator freecam and actual noclip? i added noclip only for the reason so admins can add fake triggers easily for maps that dont have real ones set up yet

With version 1.3, actually someone in my server use noclip to skip (but sv_cheats 0 ? I can see they try noclip in console a lot and sometimes they got it ), I don't know what the hell is this , so  just check noclip on everyone if it's possible

**Comment by DEAFPS** [comment]
> With version 1.3, actually someone in my server use noclip to skip (but sv_cheats 0 ? I can see they try noclip in console a lot and sometimes they got it ), I don't know what the hell is this , so just check noclip on everyone if it's possible

it might be either a map that forced sv_cheats to 1 or a current cs2 bug that makes spectator freecam players show up as  regular players

**Comment by LaplaceTor** [comment]
> > With version 1.3, actually someone in my server use noclip to skip (but sv_cheats 0 ? I can see they try noclip in console a lot and sometimes they got it ), I don't know what the hell is this , so just check noclip on everyone if it's possible
> 
> it might be either a map that forced sv_cheats to 1 or a current cs2 bug that makes spectator freecam players show up as regular players

After a lot report, some maps would force  sv_cheats 1 .....and now there's a bug, mp_roundtime cannot set as 0 , min is 0.1 and when time goes end it would restartgame and some maps would exec its config when round start

**Comment by DEAFPS** [comment]
> mp_roundtime cannot set as 0

just use mp_ignore_round_win_conditions 1 with a rtv plugin until 0.1.4 is out of testing.
btw if you want a test build yourseld hit me up on discord: `.deafps`
