### ISSUE TITLE
Issues with !prevcp

### ISSUE THREAD

**Issue by xpara97** [DEAFPS/SharpTimer#3]
**Ubuntu 22.04, dockered CS2**
**CSSharp v77** (https://github.com/roflmuffin/CounterStrikeSharp/releases/tag/v77)
**Metamod Build1270**

**Issue**: The !prevcp command, which is intended to teleport players to previous checkpoints, is not functioning correctly. Despite having multiple checkpoints set (e.g., 4 checkpoints), using !prevcp always teleports the player to the latest checkpoint.

**Reproduce:**
Create multiple checkpoints -> !prevcp

**Feature Request:**
A feature that enables players to teleport to specific checkpoints using a command format such as !tp [checkpoint_number]. This feature would offer players greater control across bhop/surf etc.../ and improve their ability to practice timers with various checkpoints.

**Comment by DEAFPS** [comment]
this will be fixed in the next release :)
