### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by LaplaceTor** [DEAFPS/SharpTimer#30]
[SharpTimerERROR] Exception in trigger_multiple OnStartTouch hook: Could not find a part of the path '/home/container/game/csgo/cfg/SharpTimer/PlayerRecords/surf_lockdown.json/_bonus1'.

**Comment by DEAFPS** [comment]
thx for reporting i totally overseen that one!

**Comment by DEAFPS** [comment]
added a hotfix for this in the pre-release 0.1.7, i also will continue to work on fixing the mem leak
