### ISSUE TITLE
How to change zones length if is possible ?

### ISSUE THREAD

**Issue by BorislavKolev1994** [DEAFPS/SharpTimer#35]
Hi guys,
I want to change and re-adjust the zones length and add some checkpoints on some maps (surf server), but unfortunately, i didn't find exactly where I can do this adjustment, is there any possibility of doing this?

**Comment by DEAFPS** [comment]
you can override manual zone height using sharptimer_fake_trigger_height

im not planning on adding manual checkpoint, stage or bonus zoning as most maps have built in triggers for that. manual zoning should always only be the last resort in case a map is poorly ported without any timer triggers

**Comment by BorislavKolev1994** [comment]
Hi DEAFPS, 
as I tried the command (via executing in the console or setting it up in config.cfg or custom_exec) it didn't work correctly, could please advise me where or how exactly this command has to be executed? I would like just to re-adjust the start and the end zones height nothing else. ❤️

**Comment by DEAFPS** [comment]
> Hi DEAFPS, as I tried the command (via executing in the console or setting it up in config.cfg or custom_exec) it didn't work correctly, could please advise me where or how exactly this command has to be executed? I would like just to re-adjust the start and the end zones height nothing else. ❤️

you can just place it into config.cfg but i forgot to mention that it will only work with manually added zones

**Comment by DEAFPS** [comment]
manual zoning tool was slightly reworked in v0.2.0. you should be able to zone the maps more easily now.
