### ISSUE TITLE
BHOP - Custom zones for bonus  

### ISSUE THREAD

**Issue by PatricNox** [DEAFPS/SharpTimer#36]
This is an example on bhop_bridge_cybershoke where i had to use the !addzone commands to make start/end zones.
There is a bonus tp here but i cannot set the zones for it, and its not done automatically

![image](https://github.com/DEAFPS/SharpTimer/assets/31646653/6338f421-6d14-4a3c-a71e-b1004a33b777)

![Uploading image.png…]()

Bonus: maybe !b for bonus spawn?

**Comment by DEAFPS** [comment]
manually zoning bonuses isnt supported and i dont really plan on adding manual bonus zoning support. manual zoning is only meant to be a workaround for bad map ports that dont have triggers included. its up for the mappers to add proper map triggers into their maps for sharptimer and other plugins to hook them

perhaps write a nice comment on the workshop page for this map for the mapper to add proper triggers to it

**Comment by PatricNox** [comment]
> manually zoning bonuses isnt supported and i dont really plan on adding manual bonus zoning support. manual zoning is only meant to be a workaround for bad map ports that dont have triggers included. its up for the mappers to add proper map triggers into their maps for sharptimer and other plugins to hook them
> 
> perhaps write a nice comment on the workshop page for this map for the mapper to add proper triggers to it

Thanks for reply, I don't seem to get any zones though on any bhop map - am I missing something in the setup?

**Comment by PatricNox** [comment]
Also, since the new update, the manual zoning commands works but aint being saved

**Comment by DEAFPS** [comment]
> Also, since the new update, the manual zoning commands works but aint being saved

use !savezones in order to save them to a mapdata json

**Comment by PatricNox** [comment]
> > Also, since the new update, the manual zoning commands works but aint being saved
> 
> use !savezones in order to save them to a mapdata json

thanks!

i think this could be related to why i dont get any automatic zones?

> [SharpTimerERROR] Error Getting Remote Data for <map>: An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

**Comment by DEAFPS** [comment]
> i think this could be related to why i dont get any automatic zones?
> 
> > [SharpTimerERROR] Error Getting Remote Data for : An invalid request URI was provided. Either the request URI must be an absolute URI or BaseAddress must be set.

no this is unrelated, mappers have to put zone triggers into their maps for the plugins to hook. most bhop map do not have them since they still think plugin devs and server operators will do that job for them
