### ISSUE TITLE
Display timesharp viewers from the player

### ISSUE THREAD

**Issue by Marfeld** [DEAFPS/SharpTimer#37]
Is there a way as a viewer to have the player display the ad? Speed, time, key presses? 

And is there a way to adjust the size of the display?

Greetings Mario

**Comment by DEAFPS** [comment]
> Is there a way as a viewer to have the player display the ad? Speed, time, key presses?
> 
> And is there a way to adjust the size of the display?
> 
> Greetings Mario

this is getting added in the next update along other stuff
