### ISSUE TITLE
valid LJ from slopes

### ISSUE THREAD

**Issue by forfex** [DEAFPS/SharpTimer#46]
I've encountered this on anubis.
When jumping from stairs I was able to hit insane LJ's (250+)

![image](https://github.com/DEAFPS/SharpTimer/assets/43018233/44385ccf-df5e-48fe-a15b-84b1cb7fa6a0)

**Comment by DEAFPS** [comment]
this should be fixed on the latest main repo along sync% if you want to build it yourself. currently im taking a short break but it should make its way into a new release soon
