### ISSUE TITLE
'Error in HandlePlayerStageTimes' When doing a run after resetting.

### ISSUE THREAD

**Issue by TootNoot** [deafps/SharpTimer#48]
Hello! When I use the reset run feature, the next time I hit a new stage, it shows the error '[SharpTimerERROR] Error in HandlePlayerStageTimes: An item with the same key has already been added. Key: (Next stage number)'
It stops showing it once you finish a run but then appears again if you use the reset feature. It doesn't seem to effect final saved times but it is annoying that it fills my console view!

1-9 stage Kitsune example
![image](https://github.com/deafps/SharpTimer/assets/54513686/5d9a3c78-2175-468e-8927-9035e7fa2f70)

**Comment by deafps** [comment]
> Hello! When I use the reset run feature, the next time I hit a new stage, it shows the error '[SharpTimerERROR] Error in HandlePlayerStageTimes: An item with the same key has already been added. Key: (Next stage number)' It stops showing it once you finish a run but then appears again if you use the reset feature. It doesn't seem to effect final saved times but it is annoying that it fills my console view!


This was a oopsie by me, should be already fixed in the next release c:
