### ISSUE TITLE
On Player connect server crashes

### ISSUE THREAD

**Issue by Exhiibits** [DEAFPS/SharpTimer#5]
Not Running anything other than Metamod and CSS with SharpTimer. Anytime someone tries to connect to the server the server instantly crashes. This is after I edit the gamemode_competitive.cfg to match the one in the read me. Before I changed the cfg file, the server would hang and crash when a team was selected

**Comment by rcon420** [comment]
> Not Running anything other than Metamod and CSS with SharpTimer. Anytime someone tries to connect to the server the server instantly crashes. This is after I edit the gamemode_competitive.cfg to match the one in the read me. Before I changed the cfg file, the server would hang and crash when a team was selected

what version of cs2fixes u run? latest build crashes my servers so im still using the old one.

**Comment by Exhiibits** [comment]
had no idea I was supposed to be using cs2fixes, but I just tried with 1.0 and same instant crash on connect

**Comment by DEAFPS** [comment]
cs2fixes is not required, you might be using a outdated CSS version

**Comment by Exhiibits** [comment]
updated to the newest version of CSS and the latest version of Timer, still crash on launch

**Comment by Exhiibits** [comment]
swapped to Release 0.0.6 of SharpTimer and v84 of CSS, still instantly crashing on player connecting

**Comment by DEAFPS** [comment]
if you are using the latest metamod, ive heard there are some issues with it.

im currently using metamod oct 26th & css v84. works fine

**Comment by Exhiibits** [comment]
I guess I should've specified that this is a Windows based server. Just tried 1255 and 1259 windows and still same issue

**Comment by Exhiibits** [comment]
Managed to get a screenshot of the console before crash, don't know how much it'll help though. Only things blurred out are the IP addresses

Windows 10 64-bit
AMD Ryzen 2600X
Radeon RX 570
16GB Ram @ 3200 mhz
<img width="660" alt="csvAyWCRVW" src="https://github.com/DEAFPS/SharpTimer/assets/82238330/509ec377-ade4-4226-85ef-352bdbab7c70">

**Comment by DEAFPS** [comment]
cs2fixes is not entirely compatible with css on linux so i can imagine the same for windows

**Comment by LielXD** [comment]
Any fix?

**Comment by LaplaceTor** [comment]
I think actually it is #10

**Comment by DEAFPS** [comment]
Windows Support for SharpTimer will be added with v0.1.0
