### ISSUE TITLE
Timer doesn't restart while standing into starting zone

### ISSUE THREAD

**Issue by Letaryat** [DEAFPS/SharpTimer#8]
**SharpTimer version:** Release v0.0.6
**CounterStrikeSharp** Version: v86
**Timer doesn't set to 0:00:00 which players can use that to manipulate time run. Timer only resets when leaving the zone not standing into it.** 

**Proof:**
Creating a checkpoint, failing a jump and walking into starting zone doesn't restart timer. Using !tp standing in starting zone teleports to checkpoint while restarting a timer. Using this, players can manipulate the timer.
https://www.youtube.com/watch?v=-O9chU_d-F8

**Probably the solution:**
Standing in a zone should set timer to 0;00:00 and stops it at that time. Right now timer sets at 0:00:00 while leaving the zone.

**Comment by DEAFPS** [comment]
Pushed a fix for that! thx for finding it!
